### ISSUE TITLE
Tab Tree Glitch

### ISSUE THREAD

**Issue by iamevilmonarch** [refact0r/midnight-fox#3]
Hi, I am using using linux debian to be exact. I have tried this repo on firefox 116 and mercury browser(fork of firefox)
As you can see in attached picture I have following issues
1. Github icon is somewhat light and if the tab is focused github icon is invisble
2. the space between tab tree and main window there is some white space theme and cross icon is half hidden

can you point me what I am doing wrong and if possible guide me
![2023-08-04_19-16](https://github.com/refact0r/midnight-fox/assets/132803399/08230bf1-064f-4c0b-b3c3-bd6168ee0d65)
![2023-08-04_21-03](https://github.com/refact0r/midnight-fox/assets/132803399/baaff0a2-50ae-4430-975a-f35c834f65ac)

**Comment by refact0r** [comment]
Looks like your top bar and window controls are a bit messed up, but that's probably due to proprietary windows elements. Since I don't have a linux machine, I can't really help you with that now. The sidebar shouldn't be affected by OS though, what version of TST do you have? Have you changed the settings much?

**Comment by iamevilmonarch** [comment]
Top bar and window control I can change and manage, the issue is with the sidebar. I have latest TST(i.e. 3.9.16) and no I 
haven't changed anything I was trying to feel the new look so I just placed chrome folder and nothing else as you can see 
from my startpage it is what it came by default I felt once I get everything working then I'll mess around.

**Comment by refact0r** [comment]
Make sure you put the right css into TST's custom css box and make sure TST's theme setting is on Proton. I don't know what could be causing that white gap though.

**Comment by iamevilmonarch** [comment]
I just checked the white gap is tree tab issue. Sorry for bothering you
